baseURL = 'https://thatsmeadarsh.github.io/'
languageCode = 'en-us'
title = 'What About Adarsh'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

[[menu.main]]
  identifier = 'posts'
  name = 'Articles'
  url = '/posts/'
[[menu.main]]
  identifier = 'services'
  name = 'Services'
  url = '/services/'
